Resources:
  dimensionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: dimensions-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: dimType
          AttributeType: S
        - AttributeName: dimId
          AttributeType: S
      KeySchema:
        - AttributeName: dimType
          KeyType: HASH
        - AttributeName: dimId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
